CREATE TABLE IF NOT EXISTS photo (
    id SERIAL PRIMARY KEY,
    trip_id INT NOT NULL REFERENCES trip(id) ON DELETE CASCADE,
    photo_url TEXT NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)